import json
from pathlib import Path
from datetime import datetime
from typing import Any, Dict
from fpdf import FPDF
import matplotlib.pyplot as plt
from io import BytesIO
import base64

# === Base directories ===
BASE_DIR = Path(__file__).resolve().parents[1]
REPORTS_DIR = BASE_DIR / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def _ensure_parent(filepath: Path):
    filepath.parent.mkdir(parents=True, exist_ok=True)


# === JSON Export ===
def save_json(results: Dict[str, Any], filename: str = "scan.json") -> str:
    filepath = REPORTS_DIR / filename
    _ensure_parent(filepath)

    out = {
        "meta": {
            "timestamp": datetime.utcnow().isoformat(),
            "scanned_hosts": len(results),
            "alive_hosts": sum(1 for r in results.values() if r.get("ports")),
        },
        "hosts": results,
    }

    with open(filepath, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2, ensure_ascii=False)

    return str(filepath.resolve())


# === PDF Report Class ===
class ReportPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        font_path = Path(__file__).resolve().parent / "DejaVuSans.ttf"
        if font_path.exists():
            self.add_font("DejaVu", "", str(font_path), uni=True)
            self.add_font("DejaVu", "B", str(font_path), uni=True)
            self.font_family = "DejaVu"
        else:
            self.font_family = "Helvetica"

    def header(self):
        if self.page_no() == 1:
            return  # No header on cover
        self.set_font(self.font_family, "B", 12)
        self.cell(0, 10, "FastPort Reconnaissance Report", ln=True, align="C")
        self.ln(2)
        self.set_font(self.font_family, size=9)
        self.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font(self.font_family, size=8)
        self.cell(0, 10, f"Page {self.page_no()} / {{nb}}", align="C")

    def section_title(self, title: str):
        self.set_font(self.font_family, "B", 12)
        self.set_fill_color(230, 230, 255)
        self.cell(0, 8, title, ln=True, fill=True)
        self.ln(3)

    def add_chart(self, title: str, data_dict: Dict[str, Any]):
        """Draw a simple bar or pie chart and embed it."""
        fig, ax = plt.subplots(figsize=(4, 2.5))
        keys, values = list(data_dict.keys()), list(data_dict.values())

        if len(keys) <= 5:
            ax.pie(values, labels=keys, autopct="%1.1f%%", startangle=140)
        else:
            ax.bar(keys, values)
            plt.xticks(rotation=30, ha="right")

        ax.set_title(title)
        plt.tight_layout()

        buf = BytesIO()
        plt.savefig(buf, format="png", dpi=120)
        plt.close(fig)
        buf.seek(0)
        self.image(buf, w=150)
        self.ln(8)


# === PDF Generator ===
def save_pdf(results: Dict[str, Any], filename: str = "scan.pdf", author: str = "FastPort Scanner") -> str:
    filepath = REPORTS_DIR / filename
    _ensure_parent(filepath)

    pdf = ReportPDF()
    pdf.alias_nb_pages()

    # === COVER PAGE ===
    pdf.add_page()
    pdf.set_font(pdf.font_family, "B", 22)
    pdf.cell(0, 20, "FastPort Network Reconnaissance Report", ln=True, align="C")
    pdf.ln(15)
    pdf.set_font(pdf.font_family, size=13)
    pdf.multi_cell(0, 8, f"""
This report summarizes host discovery and service enumeration results
generated by the FastPort asynchronous scanning engine.
    """, align="C")
    pdf.ln(20)
    pdf.set_font(pdf.font_family, size=11)
    pdf.cell(0, 8, f"Generated by: {author}", ln=True, align="C")
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
    pdf.cell(0, 8, f"Total Hosts Scanned: {len(results)}", ln=True, align="C")
    pdf.add_page()

    # === EXECUTIVE SUMMARY ===
    pdf.section_title("Executive Summary")
    total_hosts = len(results)
    active_hosts = sum(1 for r in results.values() if r.get("ports"))
    total_ports = sum(len(r.get("ports", [])) for r in results.values())

    pdf.set_font(pdf.font_family, size=11)
    pdf.multi_cell(0, 7, f"""
FastPort performed a reconnaissance scan of {total_hosts} target hosts.
Out of these, {active_hosts} responded with one or more open ports,
for a total of {total_ports} open service endpoints identified.
    """)
    pdf.ln(6)

    # Basic chart
    pdf.add_chart("Host Activity Overview", {"Active": active_hosts, "Inactive": total_hosts - active_hosts})

    # === DETAILED HOST RESULTS ===
    pdf.add_page()
    pdf.section_title("Host Details")

    for host, data in results.items():
        ports = data.get("ports", [])
        if not ports:
            continue

        pdf.set_font(pdf.font_family, "B", 12)
        pdf.set_fill_color(220, 235, 220)
        pdf.cell(0, 8, f"Host: {host}", ln=True, fill=True)
        pdf.set_font(pdf.font_family, size=10)
        pdf.cell(0, 6, f"Open Ports: {len(ports)}", ln=True)
        pdf.ln(3)

        for p in ports:
            port = p.get("port")
            proto = p.get("protocol", "tcp")
            state = p.get("state", "unknown")
            service = p.get("service", "unknown")
            banner = p.get("banner")
            version = p.get("version")

            pdf.set_font(pdf.font_family, "B", 10)
            pdf.cell(0, 6, f"Port {port}/{proto} ({state})", ln=True)
            pdf.set_font(pdf.font_family, size=9)
            pdf.cell(0, 6, f"Service: {service}", ln=True)
            if version:
                pdf.cell(0, 6, f"Version: {version}", ln=True)
            if banner:
                if len(banner) > 200:
                    banner = banner[:200] + "..."
                pdf.multi_cell(0, 5, f"Banner: {banner}")
            pdf.ln(3)

        pdf.ln(4)
        pdf.cell(0, 0, "", ln=True, border="B")
        pdf.ln(5)

    # === STATS SUMMARY ===
    pdf.add_page()
    pdf.section_title("Scan Statistics")
    ports_by_protocol = {}
    for h in results.values():
        for p in h.get("ports", []):
            proto = p.get("protocol", "tcp")
            ports_by_protocol[proto] = ports_by_protocol.get(proto, 0) + 1
    if ports_by_protocol:
        pdf.add_chart("Protocol Distribution", ports_by_protocol)

    # === FINALIZATION ===
    pdf.output(str(filepath))
    return str(filepath.resolve())
